<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Crear</name>
   <tag></tag>
   <elementGuidId>7cd4d33e-c8e8-4de9-a4ec-92b7f6e531c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Crear')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b205e8e2-900c-487a-afae-0a9ce899e2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary</value>
      <webElementGuid>3796b9c7-ed0c-4e86-823d-e3ea61c5d3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value> /Oportunidad/Create</value>
      <webElementGuid>b54058f0-ff34-4804-9d96-367954386b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Crear </value>
      <webElementGuid>d6078e0a-5126-4232-9f43-4768f7ad5dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;nav-md&quot;]/div[@class=&quot;container body&quot;]/div[@class=&quot;main_container&quot;]/div[@class=&quot;right_col&quot;]/div[@class=&quot;card mt-3&quot;]/div[@class=&quot;card-body&quot;]/a[@class=&quot;btn btn-outline-primary&quot;]</value>
      <webElementGuid>ec8ecccf-f457-4c9f-aefb-7a445145ed80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Crear')]</value>
      <webElementGuid>f0c3dc8d-3467-4bfc-9f7d-3366bb900421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listado de Oportunidades'])[1]/following::a[1]</value>
      <webElementGuid>8fc47ff2-c870-41df-9be2-14cba6b0e061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excel'])[1]/preceding::a[1]</value>
      <webElementGuid>1e16f5d3-1457-49a5-abbe-d13f356f2443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Busca todas las oportunidades?'])[1]/preceding::a[1]</value>
      <webElementGuid>0b7d278a-7ebb-4c1a-9233-9c8990a15c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Crear']/parent::*</value>
      <webElementGuid>2a7ea099-63e8-413f-8593-848aea3cb5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, ' /Oportunidad/Create')]</value>
      <webElementGuid>7f0a2dbc-2511-431f-9fb9-5dbbfc901cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>9fa31df7-4318-4f9e-9bf3-b6ada4c88403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = ' /Oportunidad/Create' and (text() = ' Crear ' or . = ' Crear ')]</value>
      <webElementGuid>7164d7cd-3aad-4310-a23a-b81da2f0797e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
