<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Simon, Marcelo_fas fa-arrow-alt-circle-right</name>
   <tag></tag>
   <elementGuidId>1929d970-a58d-4a8c-9833-0f0b5a2ebc94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='oportunidades']/tbody/tr[6]/td[14]/span/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>380db16c-32e0-4c27-a23a-395e305b9528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-arrow-alt-circle-right</value>
      <webElementGuid>98547c9e-c8af-4844-89c4-ad5ab3ec33f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oportunidades&quot;)/tbody[1]/tr[6]/td[14]/span[1]/a[2]/i[@class=&quot;fas fa-arrow-alt-circle-right&quot;]</value>
      <webElementGuid>5b1a5ab9-e55f-42a2-a42a-a5e2912af10b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='oportunidades']/tbody/tr[6]/td[14]/span/a[2]/i</value>
      <webElementGuid>2a260b1d-3059-4a59-a9b9-9ac6ca9df2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[14]/span/a[2]/i</value>
      <webElementGuid>4eddfc93-14ea-470d-a823-4a7cffe0720f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
