<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Simon, Marcelo_far fa-trash-alt red-text</name>
   <tag></tag>
   <elementGuidId>ecb2a018-d959-48fc-9ec0-051502902fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='oportunidades']/tbody/tr[-1]/td[14]/span/a[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>95451062-a0d4-479f-84ee-299a7116fe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-trash-alt red-text</value>
      <webElementGuid>f812ce65-6f44-4942-976c-c46700656c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oportunidades&quot;)/tbody[1]/tr[6]/td[14]/span[1]/a[@class=&quot;text-danger&quot;]/i[@class=&quot;far fa-trash-alt red-text&quot;]</value>
      <webElementGuid>b70a9cbd-e69b-461d-b000-bd60019d2eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='oportunidades']/tbody/tr[6]/td[14]/span/a[4]/i</value>
      <webElementGuid>94efa647-0487-4e4d-9d5e-6a7bbf0c8613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[14]/span/a[4]/i</value>
      <webElementGuid>8e0f1996-a457-417e-98b6-21e9823ee011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
