<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Presupuesto del proveedor_Presupuesto_96d2fe</name>
   <tag></tag>
   <elementGuidId>dab8c808-4b1e-4616-b867-0927f0cd1631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PresupuestoProveedor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PresupuestoProveedor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b459ab4f-2306-4089-9246-1664ae8e6a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a71fcac-d015-4cd9-8860-628bdb681ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87266b39-11d7-4df1-9579-d32376feb649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PresupuestoProveedor</value>
      <webElementGuid>3b4717dd-dbec-4b1c-bbbf-6bfd1091adb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PresupuestoProveedor</value>
      <webElementGuid>c42eec3a-a612-491d-a529-8299e97edb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2aaee526-c21b-4820-97fc-26918fe8fee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PresupuestoProveedor&quot;)</value>
      <webElementGuid>dc614ef7-4edf-4989-b131-97908bad11d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PresupuestoProveedor']</value>
      <webElementGuid>4d1c073f-42c5-44cf-a635-2cba3e41ce7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>808c4471-5ab9-42da-9418-354a81f53d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PresupuestoProveedor' and @name = 'PresupuestoProveedor']</value>
      <webElementGuid>a2c94b3e-8014-490c-9b98-124c74174281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
