<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valor hora proveedor_ValorHora</name>
   <tag></tag>
   <elementGuidId>e9fa7160-a861-4c5a-b97f-db01b2dc2880</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValorHora</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValorHora']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>699e8627-4721-413a-923f-ba7c3c602f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31b4868a-4923-4624-9e58-9b9ed5b9bd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd359383-43d3-492c-9a87-b9aaa7310646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValorHora</value>
      <webElementGuid>d74d7fc3-b04e-4c39-8c9f-6c4e09924b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValorHora</value>
      <webElementGuid>922c9d90-7173-407c-b660-dc34f2aa13f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5bffd722-efbb-4985-9874-8eba0117b35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValorHora&quot;)</value>
      <webElementGuid>cfaa1174-df2b-4a38-9a2d-92a97ee448d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValorHora']</value>
      <webElementGuid>f9d5b778-03d4-4b85-9012-e82235c922c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>c89f82c7-a6d7-4184-9b6b-e40132eb1f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ValorHora' and @name = 'ValorHora']</value>
      <webElementGuid>7e1d18d3-cb22-4764-a8d5-429c08d24388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
