<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valor hora del servicio_ValorHoraDelServicio</name>
   <tag></tag>
   <elementGuidId>c7530527-311f-40f8-bd0b-605e609e2860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ValorHoraDelServicio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ValorHoraDelServicio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7eaeac0-8a45-4ca6-a235-db60d686fee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7001b6a4-d968-489c-8441-c20b384f0abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd374ee9-75a2-44de-8bee-434407d31145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ValorHoraDelServicio</value>
      <webElementGuid>fa624e6a-d6a0-4302-a46b-bdc3be78c9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ValorHoraDelServicio</value>
      <webElementGuid>7d82a9e2-596c-443c-aa1b-58a508f3688c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b39eeb12-366e-4612-be89-731291964899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ValorHoraDelServicio&quot;)</value>
      <webElementGuid>b715b863-eb53-45ff-87b4-08316477cb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ValorHoraDelServicio']</value>
      <webElementGuid>443bcc38-a8bc-470e-b255-d6a2caef3347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>eec0f2bf-72a4-40f5-b93a-6c72e0f3ff60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ValorHoraDelServicio' and @name = 'ValorHoraDelServicio']</value>
      <webElementGuid>ea8e5455-40f1-4eb2-9fba-d19bed15ba84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
