<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tecnologa_Tecnologia</name>
   <tag></tag>
   <elementGuidId>054bc3be-b9ef-406f-86d4-bb7899a3d9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Tecnologia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Tecnologia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4bf4c11-b001-4939-955b-4338ca789225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>59fbdbc0-dfd0-418a-95e1-355d54a59355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27525614-70af-4fb9-a690-10b656bfe5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tecnologia</value>
      <webElementGuid>d91aa9fc-8a27-4745-aa3b-11159b6e8603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Tecnologia</value>
      <webElementGuid>3ff69640-85c1-438e-8f0c-fff325465d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tecnologia&quot;)</value>
      <webElementGuid>11063946-85b0-420f-9f53-ad782b9ada53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Tecnologia']</value>
      <webElementGuid>996a5d73-adca-4d76-83ab-3ab52ecef6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>ed86817a-f211-4843-8063-8ec45eef060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Tecnologia' and @name = 'Tecnologia']</value>
      <webElementGuid>42d9e534-7e6b-41f5-9c51-609c33afadcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
