<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monto total presupuestado_MontoTotalP_9a481a</name>
   <tag></tag>
   <elementGuidId>24a4ecf7-aecc-414a-9cc8-81336e197182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MontoTotalPresupuestado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MontoTotalPresupuestado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>246fdba4-3e3a-4e2a-91b6-d96f0655d267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f06e0b98-c55c-4493-8f6f-c52afa8873e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0351fec-e80c-4d71-9700-e2856d6b69bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MontoTotalPresupuestado</value>
      <webElementGuid>f812d6bc-ee13-43fc-9792-e965ea653396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MontoTotalPresupuestado</value>
      <webElementGuid>4a5c6a96-d9a1-43ef-add5-678afb94d897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1edae23a-4f28-4d7e-96ba-2ff8ec999271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MontoTotalPresupuestado&quot;)</value>
      <webElementGuid>ea014b4c-3c33-4c1b-9014-863638d23d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MontoTotalPresupuestado']</value>
      <webElementGuid>ea262f0b-6316-4e24-886e-f25787fa9d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>94d9cb73-915f-4bd3-9462-b3dd32d5923d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'MontoTotalPresupuestado' and @name = 'MontoTotalPresupuestado']</value>
      <webElementGuid>65ec0664-96e1-4ef9-b62e-c1935d4fe9e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
