<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monto mensual presupuestado_MontoMens_635ec3</name>
   <tag></tag>
   <elementGuidId>71e3f1b4-e786-49cd-9617-df37bad31330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MontoMensualPresupuestado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MontoMensualPresupuestado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>348c6096-bd23-45b8-a5ef-5ef7b5910a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e4434f9e-c8ba-40d7-98f4-644c2a3b80ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e90c8a53-b79a-469f-88cf-ba5e46a2f819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MontoMensualPresupuestado</value>
      <webElementGuid>d33ae7eb-1832-445f-8cd0-df39c660f3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MontoMensualPresupuestado</value>
      <webElementGuid>a54461c9-122a-4341-9049-45bce3b96d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8cb92b5-b03a-4627-a741-5168eb5b933a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MontoMensualPresupuestado&quot;)</value>
      <webElementGuid>cad5382c-695e-45b9-ac07-cb69d21c5db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MontoMensualPresupuestado']</value>
      <webElementGuid>7b486f99-5569-4f8b-9799-9e985d6203e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>7005947c-25aa-4e4c-a228-ee26bfe703ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'MontoMensualPresupuestado' and @name = 'MontoMensualPresupuestado']</value>
      <webElementGuid>479f4178-ec5c-4bbf-9f84-5dc01ace077b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
