<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duracin en Meses_DuracionMeses</name>
   <tag></tag>
   <elementGuidId>df25f22f-2db1-44af-9aa3-a08d283f1516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DuracionMeses</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DuracionMeses']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f4a19b8-e0cd-41f9-abd9-19c104d85b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ffd9a558-a626-4447-8dad-9bd09b858846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fe5bb8be-e01b-4942-9000-81e8d6782b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e62508f-5d5b-49a5-a0fb-692162aa325e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Ingrese un valor entre 0 y 99</value>
      <webElementGuid>ac37b419-e97b-49ca-9656-ba5e6f885785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>cfa92146-9410-4456-951b-6dafa4354941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f4e32b9-b151-4982-92e2-973e5babb030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Duración en Meses es obligatorio</value>
      <webElementGuid>5ff440ae-71be-4a5b-a1cd-099b63d592eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DuracionMeses</value>
      <webElementGuid>e22d1cf8-e05e-4cc5-bbab-e6aef2fff0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DuracionMeses</value>
      <webElementGuid>a1f57d29-23c7-43f3-aaa8-11c3341cb0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DuracionMeses&quot;)</value>
      <webElementGuid>9c913812-23b1-4314-bb03-972fdbc8b682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DuracionMeses']</value>
      <webElementGuid>0372742a-80cf-4656-9494-45896dba101c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>2f038c34-91a3-4793-8ddb-5aa81d59b5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'DuracionMeses' and @name = 'DuracionMeses']</value>
      <webElementGuid>40d52b30-2b4d-490a-a5ce-441b77f1f878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
