<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descripcin_Descripcion</name>
   <tag></tag>
   <elementGuidId>b59b0e9a-b619-4a33-8ed9-23fa22346d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Descripcion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Descripcion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cf9ebd7-40a8-443d-850b-27879dd78305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4fcd5ab-9cd6-4399-9833-8462bb2fcc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3d9d947-8402-48d8-a097-330e7e2056f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1069c4f-c503-4664-a8e5-f162eb5c1d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Descripción es obligatorio</value>
      <webElementGuid>f9dc1e61-eb48-449c-ad94-f91b8e787d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Descripcion</value>
      <webElementGuid>c3060296-1208-4d6f-83ea-e5fcab00e25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Descripcion</value>
      <webElementGuid>2dc83107-74c7-473e-8411-f8f0574240d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Descripcion&quot;)</value>
      <webElementGuid>3bbe903e-33a0-4812-9609-ea7d26c512af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Descripcion']</value>
      <webElementGuid>3bc0b3f1-dd75-4d7f-b9a4-698e0687c9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>fb012c90-ebef-4fad-a490-38bec8bb96e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Descripcion' and @name = 'Descripcion']</value>
      <webElementGuid>40795af0-1565-442f-80a3-b99fd438355f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
