<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Volver_BotonCrear</name>
   <tag></tag>
   <elementGuidId>7654b336-2e9d-42a8-8e56-21f381428173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BotonCrear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BotonCrear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcdbaa5f-db9e-4b1e-9cdf-5156458c7926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f37bb486-f03b-43b2-8711-cf2eb519915d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Crear</value>
      <webElementGuid>85524366-2e38-4d6a-b87a-77a36242933d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BotonCrear</value>
      <webElementGuid>958f4bf4-07de-4068-9213-79bacf3dd1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AsignarDatosCliente()</value>
      <webElementGuid>65b6c032-0e09-4690-bbba-97f26469b6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>9471194b-5b1b-42fb-a22c-c98a1aa8c3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BotonCrear&quot;)</value>
      <webElementGuid>eb903ba6-6ef2-4db5-b057-76c8a3c4ce0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BotonCrear']</value>
      <webElementGuid>0101844b-c632-435a-9b89-22d96bddcfd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>09a15f23-2ac3-45a3-9e63-55ea4a5a3711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'BotonCrear']</value>
      <webElementGuid>4b7c6ce6-b353-4d7b-8346-c418bccf30ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
