<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estado_Estado</name>
   <tag></tag>
   <elementGuidId>e3fdede4-e09e-4be3-a9d3-4d901c5cdeab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Estado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Estado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13456e73-a14a-4630-a879-1ae6e415e06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28ebfd19-7295-4d0a-aa54-adc54fc8d803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8dc461c8-3737-455f-b5e1-bd9bfb603bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f2bf683-0634-43e3-a8f9-429c6a2cc4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Estado field is required.</value>
      <webElementGuid>8009ea12-b68a-40c8-917c-1acee1c32957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Estado</value>
      <webElementGuid>a2ba5378-e690-444a-9591-6cd970f93d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Estado</value>
      <webElementGuid>12ecb713-2a8a-44a8-8413-fbd1c84854dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nueva Oportunidad</value>
      <webElementGuid>53f8f1ad-ffa3-47a8-ac92-ab07d7b443d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Estado&quot;)</value>
      <webElementGuid>956e6429-51c2-4616-afa1-ba87df7454fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Estado']</value>
      <webElementGuid>e1acb76f-1bad-4bf4-be0a-81710ec2c15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>2e2bf7c2-f84e-497b-88fd-8afcb11db7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Estado' and @name = 'Estado']</value>
      <webElementGuid>7ce96726-be8d-42eb-ba98-3bbb6e7fac23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
