<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Datos Cliente_ClienteRedactado</name>
   <tag></tag>
   <elementGuidId>5fa74916-5cd1-49ec-8386-01d4e5b52a86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ClienteRedactado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ClienteRedactado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c289ee32-eadc-4a4f-9917-03e5d43c4e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d731a87a-123a-4514-bad7-ba2933453f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>faa1cc51-697d-47ce-9f18-88e14e1ebdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClienteRedactado</value>
      <webElementGuid>c1562a8b-107d-4d72-ad83-66076eb46451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClienteRedactado</value>
      <webElementGuid>2b4d4503-c9c0-4956-8f68-53c30425899c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClienteRedactado&quot;)</value>
      <webElementGuid>a10b5f2b-9aaf-4f98-b230-097c5b99ba54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ClienteRedactado']</value>
      <webElementGuid>67fb4fca-c97d-420a-883f-6b688b8a6927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>481edb4a-6072-4eba-b2a3-c3d156a63cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ClienteRedactado' and @name = 'ClienteRedactado']</value>
      <webElementGuid>a6cedc01-9d89-437d-96e2-dbb04e78c8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
