<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oportunidad Relacionada_NumeroOportun_85649c</name>
   <tag></tag>
   <elementGuidId>a1d48460-af1c-4c01-8bde-ccb826fe94cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumeroOportunidadRelacionada']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NumeroOportunidadRelacionada</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbc465f8-8cf6-4271-9fd2-94af3835154f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82918cf4-815f-40cb-ad7f-8120ff617f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ff12684e-1968-47ce-a250-72532248400f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumeroOportunidadRelacionada</value>
      <webElementGuid>dda58aec-a28f-43d3-952d-3f24531f2b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumeroOportunidadRelacionada</value>
      <webElementGuid>e3516c55-8c11-4ed9-b020-760dc7851ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f73fc8c9-56f7-43da-8461-60076b6f60ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumeroOportunidadRelacionada&quot;)</value>
      <webElementGuid>4fb3d98b-c671-48e7-b287-83121ad71cf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumeroOportunidadRelacionada']</value>
      <webElementGuid>939fe15b-c705-426e-8e97-dacf892961d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b115f6d-f61e-47be-9a09-9a6c9d5d568f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NumeroOportunidadRelacionada' and @name = 'NumeroOportunidadRelacionada']</value>
      <webElementGuid>8d23b9de-f267-48f3-836f-d523350ef28f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
