<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Lmite Presentacin_FechaLimitePr_3c87cb</name>
   <tag></tag>
   <elementGuidId>be74b771-0988-44a3-afb6-aebee7a4dacf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FechaLimitePresentacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FechaLimitePresentacion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6522b5c3-94a9-49a2-8b52-904389369669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4b252a62-d323-4b32-9a5c-97dd02378549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>26e90eb0-dc2c-45c4-8b38-b5ffd9f0ca6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-03-26</value>
      <webElementGuid>e0a5126b-9989-44d1-ab7d-469dd2e48718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aca6b7a4-33e0-4359-8ac2-9aea58eeadf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Fecha Límite Presentación field is required.</value>
      <webElementGuid>b8e297f5-8488-4664-9e0c-69af03465ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FechaLimitePresentacion</value>
      <webElementGuid>298bcd66-7e46-4ebd-adcc-cf5da6d86bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FechaLimitePresentacion</value>
      <webElementGuid>7668140f-702c-4127-8150-e9a73b2c9df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>FechaLimitePresentacion-error</value>
      <webElementGuid>796967b7-0d5c-46a8-9a7f-4cbe4a6fac72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a71f848-01ed-419b-bccc-b4ddd4c04dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FechaLimitePresentacion&quot;)</value>
      <webElementGuid>9d6a514f-6ddf-462f-893c-9042737136c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FechaLimitePresentacion']</value>
      <webElementGuid>218578eb-6bf8-4a4f-afac-c5cdf7170e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>0f195dfc-5fa7-4ea6-88d5-9c0a9083d6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'FechaLimitePresentacion' and @name = 'FechaLimitePresentacion']</value>
      <webElementGuid>7f3e5b6a-218c-4dc1-b747-f10cde0c2070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
