<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oportunidad Relacionada_NumeroOportun_85649c</name>
   <tag></tag>
   <elementGuidId>a1d48460-af1c-4c01-8bde-ccb826fe94cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NumeroOportunidadRelacionada</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumeroOportunidadRelacionada']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d8fdff3-9693-4964-a288-3090d8eb7735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a080a721-dcf1-46cc-bb0d-4bc16cb57cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>389252cd-5c6c-477f-93c6-32aee067df07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumeroOportunidadRelacionada</value>
      <webElementGuid>7236d407-17d2-469e-bf24-0086c2675353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumeroOportunidadRelacionada</value>
      <webElementGuid>3145817b-2bf1-4b68-a720-48d7f7baa76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1e0bbbca-5ae4-49b0-8abe-361d53e842be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumeroOportunidadRelacionada&quot;)</value>
      <webElementGuid>f34098d7-b91f-4a49-85c4-9640629083cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumeroOportunidadRelacionada']</value>
      <webElementGuid>c3ef904a-0e03-420d-bffc-620169f78b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4d156e9-9e22-4ff4-96cf-fb3cc67cb38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NumeroOportunidadRelacionada' and @name = 'NumeroOportunidadRelacionada']</value>
      <webElementGuid>2a16727c-d8a4-42f5-908a-8f5e7a3deb58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
