<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BajaMediaAlta</name>
   <tag></tag>
   <elementGuidId>8ccb3900-01bc-484a-89a6-2d5ed40a715b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdPrioridad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdPrioridad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d4bd7f4a-5abe-41bd-a9c0-93ba9d0752f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>008f468a-c41b-4af9-9833-133fe2fac9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>14271065-bfd1-4afe-9d10-bb3ad5934136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Prioridad es obligatorio</value>
      <webElementGuid>930811d9-d85e-4afb-a85e-000ffc4a53a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdPrioridad</value>
      <webElementGuid>d4068137-9cc5-46d6-9287-30cbe130f389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IdPrioridad</value>
      <webElementGuid>c6edb358-4b76-4cf4-b35d-8d3f076994b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baja
Media
Alta
</value>
      <webElementGuid>1041b9e6-c362-4fff-8c98-615b55978240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdPrioridad&quot;)</value>
      <webElementGuid>1307f3dd-2d67-4abe-91b5-59d8f4e06e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdPrioridad']</value>
      <webElementGuid>776de705-3a45-414b-8fdd-75b0083a1eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioridad'])[1]/following::select[1]</value>
      <webElementGuid>c40ca823-328c-400f-b4a4-c694d84decb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Límite Presentación'])[1]/following::select[1]</value>
      <webElementGuid>7a6aee2f-695f-4b8e-a71f-91ebea705102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle'])[1]/preceding::select[1]</value>
      <webElementGuid>c1c58d46-109f-4319-b108-c91aaec737d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver ⮌'])[1]/preceding::select[1]</value>
      <webElementGuid>96a6be78-d66d-4f92-822f-4e1844f1fc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/select</value>
      <webElementGuid>3a6dd4e2-5c48-405f-a079-8f00f7dfbea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdPrioridad' and @name = 'IdPrioridad' and (text() = 'Baja
Media
Alta
' or . = 'Baja
Media
Alta
')]</value>
      <webElementGuid>ddcf90da-a917-4fa5-a700-5d1e96f3518c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
