<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneODMRFP</name>
   <tag></tag>
   <elementGuidId>6e8a86d8-5c54-44ac-931b-6ac7f4dad86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IdTipoOportunidad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdTipoOportunidad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6cb0f9a4-9e20-4109-bab8-6f705edbfa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e6196bb-7f36-4113-9524-f32aa67de14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0d6a519-ca05-436a-ba98-f84f061e5d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Tipo Oportunidad es obligatorio</value>
      <webElementGuid>e032ae5c-af66-4165-8208-9799f7d12437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdTipoOportunidad</value>
      <webElementGuid>e27ba37a-3396-40f4-ac76-bfa6f8ccb7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IdTipoOportunidad</value>
      <webElementGuid>21c00b9b-f861-4aa5-819c-eb621d62f899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione
ODM
RFP
</value>
      <webElementGuid>e817c5b8-160f-454c-aa28-f7dfb616c4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdTipoOportunidad&quot;)</value>
      <webElementGuid>67eb5254-cc31-4586-bcbd-750e2ee9a626</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdTipoOportunidad']</value>
      <webElementGuid>3a3e72ad-134c-4e41-9d8d-44db3ad093a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Oportunidad'])[1]/following::select[1]</value>
      <webElementGuid>d4419629-e479-4358-a79b-8301daa65dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva oportunidad'])[1]/following::select[1]</value>
      <webElementGuid>283fb2b5-42ab-46c8-ae04-c4262eedc08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oportunidad Relacionada'])[1]/preceding::select[1]</value>
      <webElementGuid>64906084-e59d-4415-ab27-5d864da46a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Es Licitación?'])[1]/preceding::select[1]</value>
      <webElementGuid>57c3b3c0-24db-4534-a789-b6a807e77fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4b9966aa-b641-4c3c-a449-9ad776779eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdTipoOportunidad' and @name = 'IdTipoOportunidad' and (text() = 'Seleccione
ODM
RFP
' or . = 'Seleccione
ODM
RFP
')]</value>
      <webElementGuid>85bec29d-8542-4d1d-9746-18897ca81271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
