<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccioneArgentina BrasilMxicoUrugu_1e4540</name>
   <tag></tag>
   <elementGuidId>437b8c90-437b-46f6-a953-ae70bc036696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IdPais</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdPais']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>66614edd-426c-46f9-a9a7-2663b5cf9c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e995b43-97c0-4cf1-a1ab-ccc9a5e0f0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca615ddd-f0d8-410e-97ed-6c45382bf773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo País Facturación es obligatorio</value>
      <webElementGuid>e63fd199-7026-4d10-8207-9c8a604959b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdPais</value>
      <webElementGuid>377d3e40-80c9-473b-b05e-221928942926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IdPais</value>
      <webElementGuid>38772604-b22c-4373-a59e-0a0a5672cd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione
Argentina 
Brasil
México
Uruguay
Chile
EEUU
Paraguay
Colombia
Sudafrica
</value>
      <webElementGuid>7a81a1ea-cc03-49b5-8c49-4ab2eab4963a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdPais&quot;)</value>
      <webElementGuid>81505b9b-49cf-4a45-94a2-e1984d2b1549</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdPais']</value>
      <webElementGuid>ec52a32a-a334-4171-ac8e-911ff688f004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='País Facturación'])[1]/following::select[1]</value>
      <webElementGuid>bad7d571-468f-4c03-996d-1a7343e77fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::select[1]</value>
      <webElementGuid>f4d4bf7d-ae1d-412d-b81d-b92d93a885aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda'])[1]/preceding::select[1]</value>
      <webElementGuid>1a105e8f-2408-49c5-8847-db420c264a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Toma clientes de NetSuite?'])[1]/preceding::select[2]</value>
      <webElementGuid>cfc8e9fa-247d-421c-83c2-50b53b8ab067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>99137689-d0ae-47bb-868b-76129bf05259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdPais' and @name = 'IdPais' and (text() = 'Seleccione
Argentina 
Brasil
México
Uruguay
Chile
EEUU
Paraguay
Colombia
Sudafrica
' or . = 'Seleccione
Argentina 
Brasil
México
Uruguay
Chile
EEUU
Paraguay
Colombia
Sudafrica
')]</value>
      <webElementGuid>b4675064-c047-4503-8945-689d584572a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
