<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BajaMediaAlta</name>
   <tag></tag>
   <elementGuidId>8ccb3900-01bc-484a-89a6-2d5ed40a715b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IdPrioridad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdPrioridad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>789b8505-27a3-49c3-9d9a-f52241f2fccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ffdba642-7bf7-45d3-8d01-f53a560b502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4201f495-7f92-46ad-9a29-4808069dfc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Prioridad es obligatorio</value>
      <webElementGuid>b7a927ac-ba1b-4b9d-a170-474150aa83ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdPrioridad</value>
      <webElementGuid>7223f95f-8b8f-4471-86dd-861131fe2baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IdPrioridad</value>
      <webElementGuid>20b426ca-5f3d-437b-bd7e-99535915968e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baja
Media
Alta
</value>
      <webElementGuid>136caa31-06a7-427d-9f4d-a8c459f63458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdPrioridad&quot;)</value>
      <webElementGuid>d3bacf52-b019-4fc1-a22c-c6492296f2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdPrioridad']</value>
      <webElementGuid>1ae8efe1-4a21-401e-b467-cdf017c95a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioridad'])[1]/following::select[1]</value>
      <webElementGuid>5bb6687a-8d69-45bc-9371-e09af9eaa71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Límite Presentación'])[1]/following::select[1]</value>
      <webElementGuid>db172027-5c76-44fc-8511-a68d003f10c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle'])[1]/preceding::select[1]</value>
      <webElementGuid>bef44288-fe71-48aa-992f-d51903316fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver ⮌'])[1]/preceding::select[1]</value>
      <webElementGuid>5756c905-52dd-4b98-8a51-ccb13d8bec1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/select</value>
      <webElementGuid>4f97c558-6a3c-4ded-804e-c9341533e92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdPrioridad' and @name = 'IdPrioridad' and (text() = 'Baja
Media
Alta
' or . = 'Baja
Media
Alta
')]</value>
      <webElementGuid>2a159434-862d-4088-868e-4d1f599ea2ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
