<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Detalle_Detalle</name>
   <tag></tag>
   <elementGuidId>2c81ea02-2ee6-46e6-abc2-eaded7d60d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Detalle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Detalle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7661996d-264d-4742-95a6-5905b917a88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>517e443e-979c-430e-bcd0-fe92711a7540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0abd93b-ddba-4f6a-9569-d6c097cc7a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Detalle es obligatorio</value>
      <webElementGuid>cc11cb4e-e1eb-4c79-a0d9-d4f182701e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detalle</value>
      <webElementGuid>94f5a52d-ea3a-41bc-8944-d643105248e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detalle</value>
      <webElementGuid>b5cb3d6c-9532-49fa-854f-09067a7997ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>c75d4354-5114-4047-b4b6-d7d5d5305c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Detalle-error</value>
      <webElementGuid>1bd13bbb-cff2-447c-8706-1448e081d045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detalle&quot;)</value>
      <webElementGuid>aa024da3-6475-433a-81ee-68be2d9ee7c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Detalle']</value>
      <webElementGuid>2fab0e67-a8e7-43eb-82bc-3777848208ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b21b687b-0346-48fc-868e-92ada3f7c061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Detalle' and @name = 'Detalle']</value>
      <webElementGuid>bfa7be6c-3944-4f4c-8440-e56c128bb3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
