<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Detalle_Detalle</name>
   <tag></tag>
   <elementGuidId>2c81ea02-2ee6-46e6-abc2-eaded7d60d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Detalle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Detalle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0fdd8b48-b712-494f-a251-433bc288f496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>70ebe0e5-87b9-4942-858b-700e6dbed903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f6f420f-b2d1-47ee-9622-5c7e2604b5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>El campo Detalle es obligatorio</value>
      <webElementGuid>b49e9e2b-ef0a-4867-b28d-b786e050de51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Detalle</value>
      <webElementGuid>50c63e3f-e864-4344-92cc-b0b31f5f8a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Detalle</value>
      <webElementGuid>33a23a44-f7d9-41a0-99e4-eaf82051cce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-validation-error</value>
      <webElementGuid>c5674cdc-80f7-4999-80de-57cd7add3c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Detalle-error</value>
      <webElementGuid>a7715ef0-5584-40fc-88be-f060a25472f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Detalle&quot;)</value>
      <webElementGuid>28642bc5-f988-4373-87f7-47a692bf7fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Detalle']</value>
      <webElementGuid>8fa0c968-77f8-4831-a1fa-fdca8c8c903f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3615f743-6503-4494-b01e-f0a2d4bc53fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Detalle' and @name = 'Detalle']</value>
      <webElementGuid>476437b7-9737-465c-b413-eafbb498276b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
