<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Si_fas fa-pencil-alt</name>
   <tag></tag>
   <elementGuidId>380ba491-7003-4b65-997f-35f6d4492aec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='paises']/tbody/tr[22]/td[7]/span/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0903ad5a-7b93-406c-ae46-eea482b3f2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-pencil-alt</value>
      <webElementGuid>cefc6776-f397-4946-9fe3-375984d279f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paises&quot;)/tbody[1]/tr[22]/td[7]/span[1]/a[2]/i[@class=&quot;fas fa-pencil-alt&quot;]</value>
      <webElementGuid>9a19fd4f-4b1f-4c1a-a49e-27608d934fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='paises']/tbody/tr[22]/td[7]/span/a[2]/i</value>
      <webElementGuid>f77acbf6-cca1-4268-908a-0bdc2cf3257c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[7]/span/a[2]/i</value>
      <webElementGuid>e9f16c95-2647-4dea-ad31-bf2b3afcb1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
