<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cerrar_ConfirmarComercial</name>
   <tag></tag>
   <elementGuidId>8070f998-9793-4ccc-bcb9-f0bc4d9de394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmarComercial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmarComercial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70cef82b-468f-4de2-843e-2c61a12eea09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e005a60-616f-405c-b512-f88d0edab437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmarComercial</value>
      <webElementGuid>064a1cde-c2f5-41e3-8451-dc311e05f1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>188af5e8-6d02-4c22-a4ec-47b88d1cc3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>65269eab-9586-4681-b898-98fa655ce9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmarComercial&quot;)</value>
      <webElementGuid>f5c59651-2c80-4e1b-91b2-dfd3e5d4822d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmarComercial']</value>
      <webElementGuid>a055d258-de68-470b-a07c-5aeba3682cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalComercial']/div/div/div[3]/input</value>
      <webElementGuid>b39f3918-6d14-4625-ae8d-612c74a3d0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div[3]/input</value>
      <webElementGuid>45e69b00-b9c4-489a-9f04-79a28767e67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ConfirmarComercial']</value>
      <webElementGuid>a1c9dfcf-e869-4397-aa49-10209152cb78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
