<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cerrar_ConfirmarProveedor</name>
   <tag></tag>
   <elementGuidId>e36194b5-1d50-4b68-b6dd-cc2645d1595a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmarProveedor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmarProveedor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffa1570b-5aeb-4736-a18a-aca889b3a5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fceb328e-9b58-42b9-b764-3ff6c3a659ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmarProveedor</value>
      <webElementGuid>a27210c9-e144-47d8-aa7c-6205139351b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>f4110b01-2575-4980-91cb-fd9fe75da549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success valid</value>
      <webElementGuid>016370ae-cac7-4b11-b7b3-21b8c961a5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>148212ec-2dc4-48b7-a4e9-16e1447cce45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmarProveedor&quot;)</value>
      <webElementGuid>0be6e8ea-14c7-4b4f-8339-795576eb1818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmarProveedor']</value>
      <webElementGuid>b5f33c14-54f9-42d2-ac7f-d17b99fbe021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalProveedor']/div/div/div[3]/input</value>
      <webElementGuid>0e8cecf0-a64a-4d5e-8f54-c4908f678e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div/div/div[3]/input</value>
      <webElementGuid>e8200e22-e426-4175-a134-1eaca288a8ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ConfirmarProveedor']</value>
      <webElementGuid>e8c21a6f-b5e8-4a3f-8885-696986f5946c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
