<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cerrar_ConfirmarEnviarAPreventa</name>
   <tag></tag>
   <elementGuidId>352b190a-1e81-4f21-b4c6-344a74c82d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ConfirmarEnviarAPreventa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConfirmarEnviarAPreventa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3e76cb2-1d55-42eb-b31a-1df5e3be1287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08368490-5d1b-4857-ad23-81fb8516ef87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmarEnviarAPreventa</value>
      <webElementGuid>68ac85e2-3b7e-482e-ad09-fda77606f216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar Envio A Preventa</value>
      <webElementGuid>d911dc8d-6c43-43bf-ab52-56eba3481d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>cc9afec9-256c-415c-be29-4a96436d11db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmarEnviarAPreventa&quot;)</value>
      <webElementGuid>7bb25e1e-a767-4073-9469-04cf28597242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConfirmarEnviarAPreventa']</value>
      <webElementGuid>fb211b8b-823f-445e-92f2-b47c64dc6be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEnviarAPreventa']/div/div/div[3]/input</value>
      <webElementGuid>64df457a-54a3-4801-8623-900f0b71e0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>06ea92dc-1a54-4594-81d3-b07952fe91f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ConfirmarEnviarAPreventa']</value>
      <webElementGuid>da6cc8a9-f1d2-4116-83ef-adc33ca4bd1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
