<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Comentario_comentario</name>
   <tag></tag>
   <elementGuidId>28cea0ba-1f8d-450f-a3a4-808fedbb5898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comentarioProveedor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='comentarioProveedor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6774dcb3-f99a-4e85-8a3e-1a42713b3c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9f513fb-7856-4f46-811d-8020e95e2cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comentarioProveedor</value>
      <webElementGuid>916a4ffd-893d-4425-836b-96f36d2b1b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comentario</value>
      <webElementGuid>d07644a1-695a-498e-bef3-43091e0fcdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>893760a5-75eb-4cb1-a397-bd67ee76d5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comentarioProveedor&quot;)</value>
      <webElementGuid>683273fe-f4f6-4d18-b617-160fd654e53e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='comentarioProveedor']</value>
      <webElementGuid>c06e37cb-808a-4e50-8a75-e848b3c3c449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalProveedor']/div/div/div[2]/div/input</value>
      <webElementGuid>7e52bb92-0b2a-4b09-896d-ad775d25a1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div/div/div[2]/div/input</value>
      <webElementGuid>ea88ee2b-3fbb-4aaf-9d47-ffa2ef461528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'comentarioProveedor' and @name = 'comentario']</value>
      <webElementGuid>c485f88b-ee12-4713-b353-98edb57a8383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='comentarioComercial']</value>
      <webElementGuid>92546073-44e4-4362-9fac-d92bc085ed25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalComercial']/div/div/div[2]/div/input</value>
      <webElementGuid>cbeeb36d-eeea-47ad-83be-a343f1df6ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>5c868149-eaf0-4372-a789-2ddd1fbe8651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'comentarioComercial' and @name = 'comentario']</value>
      <webElementGuid>af96cdf4-038a-4081-a1c1-fe0c9c023c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='comentarioEnviarAPreventa']</value>
      <webElementGuid>355cb39f-8bb9-4b44-8d2f-7a594d7a94fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalEnviarAPreventa']/div/div/div[2]/div/input</value>
      <webElementGuid>941f66d9-ed6f-483d-854b-75baaf72e614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/input</value>
      <webElementGuid>e9dcf1b4-b9ef-4610-85cd-23b5a3ac53ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'comentarioEnviarAPreventa' and @name = 'comentario']</value>
      <webElementGuid>e2316752-7c84-4573-be21-032515c33579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
